export { default as Banner } from './Banner';
export { default as Features } from './Features';
export { default as Signup } from './Signup';
export { default as Mission } from './Mission';
export { default as Challenges } from './Challenges';
export { default as Advantage } from './Advantage';
export { default as Recommendation } from './Recommendation';
export { default as Download } from './Download';
export { default as Footer } from './Footer';
